<?php

namespace App\Ai\Agents;

use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Ai\Concerns\RemembersConversations;
use Laravel\Ai\Contracts\Agent;
use Laravel\Ai\Contracts\Conversational;
use Laravel\Ai\Contracts\HasStructuredOutput;
use Laravel\Ai\Contracts\HasTools;
use Laravel\Ai\Contracts\Tool;
use Laravel\Ai\Messages\Message;
use Laravel\Ai\Promptable;
use Laravel\Ai\Providers\Tools\WebFetch;
use Stringable;

class MorpheusAgent implements Agent, Conversational, HasStructuredOutput, HasTools
{
    use Promptable, RemembersConversations;

    /**
     * Get the instructions that the agent should follow.
     */
    public function instructions(): Stringable|string
    {
        return 'You are MORPHEUS, a Senior Auditor specialized in UX/UI and Socio-Technical Security.
Analyze ALL the provided interaction steps (images in chronological order).

PAY ATTENTION TO THE IMAGE FORMAT (SCRIBE):
The images you are analyzing are full rendered PDF pages generated by the “Scribe” tool.
Each image contains some “noise” that you MUST IGNORE: header text, written instructions at the top or bottom (e.g. “Click the…”), watermarks (“Made with Scribe”), and page numbers.
You MUST FOCUS EXCLUSIVELY on the screenshot of the user interface (UI) embedded in the center of the page.
The element the user is interacting with is highlighted by Scribe with an orange circle. Use that circle to understand the focus of the action.';
    }

    /**
     * Get the tools available to the agent.
     *
     * @return Tool[]
     */
    public function tools(): iterable
    {
        return [
            new WebFetch,
        ];
    }

    /**
     * Get the agent's structured output schema definition.
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'value' => $schema->string()->required(),
            'evaluation_found' => $schema->boolean()->required(),
            'result' => $schema->object( fn ($schema) => [
                'artifact_id' => $schema->number()->required()->description('The ID of the artifact where the violation is visible. Return only the clean artifact ID, for example: 1.'),
                'visual_element_description' => $schema->string()->required()->description('Describe what is wrong in the user interface or in the interaction flow.'),
                'internal_reasoning' => $schema->string()->required()->description('Provide the technical explanation of why this is a violation of the current Evaluation Pattern.'),
                'pragmatic_explanation' => $schema->string()->description(
                    'Provide a brutally pragmatic executive summary for the technical team, in no more than 3 sentences and without bullet points. Follow this exact structure: 1) THE BUG: what is wrong in the interface. 2) THE IMPACT: what block, error, or frustration it causes for the user. 3) THE SOLUTION: the exact technical or design action required to fix it. Example tone and length: "The X button has no active state. Because the user receives no visual feedback, they may click it twice and submit duplicate data. Add a loading spinner and disable the button after the first click."'
                ),
                'severity' => $schema->string()->enum(['low', 'medium', 'high'])->required()->description('The severity of the violation.'),
                //'executive_question' => [$orgQuestion],
            ])->required(),
        ];
    }
}
