<?php

namespace App\Ai\Agents;

use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Ai\Concerns\RemembersConversations;
use Laravel\Ai\Contracts\Agent;
use Laravel\Ai\Contracts\Conversational;
use Laravel\Ai\Contracts\HasStructuredOutput;
use Laravel\Ai\Contracts\HasTools;
use Laravel\Ai\Contracts\Tool;
use Laravel\Ai\Messages\Message;
use Laravel\Ai\Promptable;
use Laravel\Ai\Providers\Tools\WebFetch;
use Stringable;

class MorpheusAgent implements Agent, Conversational, HasStructuredOutput
{
    use Promptable, RemembersConversations;

    /**
     * Get the instructions that the agent should follow.
     */
    public function instructions(): Stringable|string
    {
        return 'You are MORPHEUS, a Senior Auditor specialized in UX/UI and Socio-Technical Security.
Analyze ALL the provided interaction steps (images in chronological order).

PAY ATTENTION TO THE IMAGE FORMAT (SCRIBE):
The images you are analyzing are full rendered PDF pages generated by the “Scribe” tool.
Each image contains some “noise” that you MUST IGNORE: header text, written instructions at the top or bottom (e.g. “Click the…”), watermarks (“Made with Scribe”), and page numbers.
You MUST FOCUS EXCLUSIVELY on the screenshot of the user interface (UI) embedded in the center of the page.
The element the user is interacting with is highlighted by Scribe with an orange circle. Use that circle to understand the focus of the action.
For each image, an URL can be provided to fetch the web content of the analyzed system.
If an URL is provided to the relative image, implement it in the analysis for a more precise result (use web fetch tool)';
    }



    /**
     * Get the agent's structured output schema definition.
     */
    public function schema(JsonSchema $schema): array
    {
        {
            return [
                'value' => $schema->string()->required(),

                'violation_found' => $schema->boolean()->required(),

                'result' => $schema->object(fn ($schema) => [
                    'title' => $schema->string()->required()->description(
                        'A concise title for the finding, maximum one short sentence. Example: "Opaque password reset CTA in a high-risk banking flow".'
                    ),

                    'description' => $schema->string()->required()->description(
                        'Describe the finding in a complete but concise way, explaining the issue observed in the interface or interaction flow.'
                    ),

                    'artifact_id' => $schema->number()->required()->description(
                        'The ID of the artifact where the violation is visible. Return only the clean artifact ID, for example: 1.'
                    ),

                    'visual_element_description' => $schema->string()->required()->description(
                        'Describe the specific visual element, screen area, component, or interaction flow where the violation is visible.'
                    ),

                    'internal_reasoning' => $schema->string()->required()->description(
                        'Provide the technical explanation of why this is a violation of the current Evaluation Pattern.'
                    ),

                    'impact' => $schema->string()->required()->description(
                        'Explain the potential impact of this violation on the user, the organization, cybersecurity risk, or the related human factors.'
                    ),

                    'pragmatic_explanation' => $schema->string()->required()->description(
                        'Provide a pragmatic executive summary for the technical team, in no more than 3 sentences and without bullet points.'
                    ),

                    'severity' => $schema->string()
                        ->enum(['low', 'medium', 'high'])
                        ->required()
                        ->description('The severity of the violation.'),
                ])->required(),
            ];
        }
    }
}
